services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root:password@db:3306/app_development?ssl_mode=disabled
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql/conf.d:/etc/mysql/conf.d
    command: 
     - --default-authentication-plugin=mysql_native_password
     - --bind-address=0.0.0.0
     - --skip-name-resolve

  test:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      RAILS_ENV: test
      DATABASE_URL: mysql://root:password@test-db:3306/app_test?ssl_mode=disabled
    depends_on:
      - test-db
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec rspec"

  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_test
    ports:
      - "3308:3306"
    command:
     - --default-authentication-plugin=mysql_native_password
     - --bind-address=0.0.0.0
     - --skip-name-resolve


volumes:
  mysql_data:
  bundle_cache: